> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



#  5 Functins from PyTorch on Tensor operation

PyTorch is a Python machine learning package based on Torch, which is an open-source machine learning package based on the programming language Lua.PyTorch is also great for deep learning research and provides maximum flexibility and speed. 

- Torch.cat
- Torch.chunk
- Torch.reshape 
- Torch.split
- Torch.take

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
#!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.cat 

Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [7]:
x = torch.randn(2, 3)
x

tensor([[ 0.7169,  1.1573,  0.5392],
        [ 0.6968,  0.7099, -0.1782]])

In [9]:
# Example 1 - working 
A=torch.cat((x, x, x), 0)
A

tensor([[ 0.7169,  1.1573,  0.5392],
        [ 0.6968,  0.7099, -0.1782],
        [ 0.7169,  1.1573,  0.5392],
        [ 0.6968,  0.7099, -0.1782],
        [ 0.7169,  1.1573,  0.5392],
        [ 0.6968,  0.7099, -0.1782]])

In the above explain we can see that we are concatinating the tensors with exiting axis or dimension

In [10]:
# Example 2 - working
B=torch.cat((x, x, x), 1)
B

tensor([[ 0.7169,  1.1573,  0.5392,  0.7169,  1.1573,  0.5392,  0.7169,  1.1573,
          0.5392],
        [ 0.6968,  0.7099, -0.1782,  0.6968,  0.7099, -0.1782,  0.6968,  0.7099,
         -0.1782]])

In the above explain we can see that we are concatinating the tensors without changing axis 1

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
torch.cat((A,B),1)

RuntimeError: Sizes of tensors must match except in dimension 1. Got 6 and 2 in dimension 0 (The offending index is 1)

As you see in above example two different shape tensors cannot be conacatinated.

This function can be used when you have to  join tensors with existing axis

Let's save our work using Jovian before continuing.

In [12]:
!pip install jovian --upgrade --quiet

In [13]:
import jovian

In [47]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations


'https://jovian.ai/pavankareti/01-tensor-operations'

## Function 2 - torch.chunk

Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.

In [32]:
# Example 1 - working
torch.chunk(B,3,1)

(tensor([[ 0.7169,  1.1573,  0.5392],
         [ 0.6968,  0.7099, -0.1782]]),
 tensor([[ 0.7169,  1.1573,  0.5392],
         [ 0.6968,  0.7099, -0.1782]]),
 tensor([[ 0.7169,  1.1573,  0.5392],
         [ 0.6968,  0.7099, -0.1782]]))

The input tensor got splitted into 3 chunks(groups) as mentioned in parameters.

In [37]:
# Example 2 - working
torch.chunk(A,4,0)

(tensor([[ 0.7169,  1.1573,  0.5392],
         [ 0.6968,  0.7099, -0.1782]]),
 tensor([[ 0.7169,  1.1573,  0.5392],
         [ 0.6968,  0.7099, -0.1782]]),
 tensor([[ 0.7169,  1.1573,  0.5392],
         [ 0.6968,  0.7099, -0.1782]]))

If the tensor is size not  divided then torch.chunk gives output until its divided.

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
torch.chunk(A,4,2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

It does not work if the dimension out of range.

This function can be used to divide a input data into chunks in specified dimension.

In [39]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations


'https://jovian.ai/pavankareti/01-tensor-operations'

## Function 3 - torch.reshape

	
Returns a tensor with the same data and number of elements as input, but with the specified shape.

In [45]:
# Example 1 - working
torch.reshape(A,(3,6))

tensor([[ 0.7169,  1.1573,  0.5392,  0.6968,  0.7099, -0.1782],
        [ 0.7169,  1.1573,  0.5392,  0.6968,  0.7099, -0.1782],
        [ 0.7169,  1.1573,  0.5392,  0.6968,  0.7099, -0.1782]])

It simply gives output reshaping in a specified shape without changing input data.

In [46]:
# Example 2 - working
torch.reshape(A,(-1,))

tensor([ 0.7169,  1.1573,  0.5392,  0.6968,  0.7099, -0.1782,  0.7169,  1.1573,
         0.5392,  0.6968,  0.7099, -0.1782,  0.7169,  1.1573,  0.5392,  0.6968,
         0.7099, -0.1782])

A single dimension may be -1, in which case it’s inferred from the remaining dimensions and the number of elements in input

In [48]:
# Example 3 - breaking (to illustrate when it breaks)
torch.reshape(A,(3,3))

RuntimeError: shape '[3, 3]' is invalid for input of size 18

It can delete or add data toinput to reshape . It can reshape a tensor for valid input size.

This function can be used to reshape the tensors.

In [49]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations


'https://jovian.ai/pavankareti/01-tensor-operations'

## Function 4 - torch.split

Splits the tensor into chunks. Each chunk is a view of the original tensor.

In [50]:
a = torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [51]:
# Example 1 - working
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

The function spilts tensor into equal chunks if possible or Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size.

In [52]:
# Example 2 - working
torch.split(a, [1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

By using tensor.split we can split the function to a specified shape and specified number of chunks

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
torch.split(a, [2,4])

RuntimeError: start (2) + length (4) exceeds dimension size (5).

dimension size is fixed according to the input so reshape can be done within that dimension.

It can be used to Split the tensor into chunks. Each chunk is a view of the original tensor

In [54]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations


'https://jovian.ai/pavankareti/01-tensor-operations'

## Function 5 - torch.take

Returns a new tensor with the elements of input at the given indices.

In [55]:
# Example 1 - working
torch.take(a, torch.tensor([0, 2, 5]))

tensor([0, 2, 5])

 The input tensor is treated as if it were viewed as a 1-D tensor

In [56]:
# Example 2 - working
torch.take(a, torch.tensor([0, 2]))

tensor([0, 2])

The result takes the same shape as the indices.

In [70]:
# Example 3 - breaking (to illustrate when it breaks)
torch.take(a,torch.randn(2, 3))

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'index' in call to _th_take

Float values cannot be used

This is useful to return a new tensor with the elements of input at the given indices or to overwrite a tensor.

In [71]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations


'https://jovian.ai/pavankareti/01-tensor-operations'

## Conclusion

In this notebook you can find 5 efficient PyTorch tensor operations along with their explanation and working by using examples.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [72]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations


'https://jovian.ai/pavankareti/01-tensor-operations'

In [73]:
jovian.submit(assignment="zerotogans-a1")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "pavankareti/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/pavankareti/01-tensor-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
